language: ruby
rvm:
  - 2.1.1
before_install: gem install bundler --pre
script:
  - RAILS_ENV=test bundle exec rake db:reset
  - bundle exec rake spec
bundler_args:
  - -j2
  - --without development
deploy:
  provider: heroku
  app: yoteach
  run:
    - "rake db:migrate"
    - restart
  api_key:
    secure: K3+GYhFAV4Yx8Gcyn5p8IAWuM8lllWpwmtqOQ8524e+AuZKbzl+5Th3Hy1XwaeIYHFgrTw3m2XT9KDLAWQSFJtgST7BBh2T2z0rHD4dDYWYjw1/mouwtX/zjU/qHWTISTFBJOHcg6h5L8dz254L+cFSLeliA2I8gB8LBQNb52wY=
notifications:
  email:
    recipients:
      - alectower@gmail.com
      - lukegtower@gmail.com
    on_success: always
    on_failure: always
