common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: hippie

development:
  <<: *common
  database: yo_teach_development

test:
  <<: *common
  database: yo_teach_test

production:
  <<: *common
  database: yo_teach_production
